"""empty message

Revision ID: 1009be77dacd
Revises: None
Create Date: 2014-08-21 01:54:09.141000

"""

# revision identifiers, used by Alembic.
revision = '1009be77dacd'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    ### end Alembic commands ###
