"""empty message

Revision ID: 1ea1cd37c30b
Revises: 1009be77dacd
Create Date: 2014-08-21 02:11:33.610000

"""

# revision identifiers, used by Alembic.
revision = '1ea1cd37c30b'
down_revision = '1009be77dacd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=255), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'user', sa.Column('checkcode', sa.Integer(), nullable=True))
    op.add_column(u'user', sa.Column('country', sa.String(length=255), nullable=False))
    op.add_column(u'user', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column(u'user', sa.Column('gender', sa.String(length=255), nullable=False))
    op.add_column(u'user', sa.Column('hobby', sa.Text(), nullable=True))
    op.add_column(u'user', sa.Column('intro', sa.Text(), nullable=True))
    op.add_column(u'user', sa.Column('korea_school', sa.String(length=255), nullable=False))
    op.add_column(u'user', sa.Column('like', sa.Text(), nullable=True))
    op.add_column(u'user', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column(u'user', sa.Column('nickname', sa.String(length=255), nullable=True))
    op.add_column(u'user', sa.Column('orgin_school', sa.String(length=255), nullable=False))
    op.add_column(u'user', sa.Column('password', sa.String(length=255), nullable=False))
    op.add_column(u'user', sa.Column('region', sa.String(length=255), nullable=False))
    op.add_column(u'user', sa.Column('state', sa.String(length=20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'user', 'state')
    op.drop_column(u'user', 'region')
    op.drop_column(u'user', 'password')
    op.drop_column(u'user', 'orgin_school')
    op.drop_column(u'user', 'nickname')
    op.drop_column(u'user', 'name')
    op.drop_column(u'user', 'like')
    op.drop_column(u'user', 'korea_school')
    op.drop_column(u'user', 'intro')
    op.drop_column(u'user', 'hobby')
    op.drop_column(u'user', 'gender')
    op.drop_column(u'user', 'email')
    op.drop_column(u'user', 'country')
    op.drop_column(u'user', 'checkcode')
    op.drop_table('language')
    ### end Alembic commands ###
