"""empty message

Revision ID: 26a6a3c32d3e
Revises: 1ea1cd37c30b
Create Date: 2014-08-23 01:28:52.183000

"""

# revision identifiers, used by Alembic.
revision = '26a6a3c32d3e'
down_revision = '1ea1cd37c30b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('event_date', sa.String(length=255), nullable=False),
    sa.Column('event_date_created', sa.DateTime(), nullable=True),
    sa.Column('place_school', sa.String(length=255), nullable=True),
    sa.Column('contact', sa.String(length=255), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('limited_member_num', sa.Integer(), nullable=True),
    sa.Column('attend_member_num', sa.Integer(), nullable=True),
    sa.Column('recommend_count', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    ### end Alembic commands ###
